# {process.env.NODE_ENV} to know in the components if we are in development or production
# FROM node:alpine
FROM node:20.10
WORKDIR /client
COPY package.json .
RUN npm i
COPY . .
CMD ["npm", "run" , "dev"]

# We use node:alpine as our base image. This image is a minimal Node.js image based on Alpine Linux with a complete package index and only 5 MB in size